package:
  name: geoalchemy2
  version: !!str 0.3.0.dev1

source:
  fn: GeoAlchemy2-0.3.0.dev1.tar.gz
  url: https://pypi.python.org/packages/source/G/GeoAlchemy2/GeoAlchemy2-0.3.0.dev1.tar.gz
  md5: b6ce81fd5ab986f3f7743342e1196ede

requirements:
  build:
    - python
    - sqlalchemy

  run:
    - python
    - sqlalchemy

test:
  imports:
    - geoalchemy2

about:
  home: https://github.com/geoalchemy/geoalchemy2
  license: MIT
  summary: Using SQLAlchemy with Spatial Databases
