package:
  name: python-magic
  version: !!str 0.4.13

source:
  fn: python-magic-0.4.13.tar.gz
  url: https://pypi.python.org/packages/65/0b/c6b31f686420420b5a16b24a722fe980724b28d76f65601c9bc324f08d02/python-magic-0.4.13.tar.gz
  md5: bbf309c8eeb414ed9957aa3a5e43a869
  
build:
  number: 1

requirements:
  build:
    - python
    - pip

  run:
    - python

about:
  home: https://github.com/ahupp/python-magic
  license: MIT
  summary: A python wrapper for libmagic
