package:
  name: easygui
  version: !!str 0.98.1

source:
  fn: easygui-0.98.1.tar.gz
  url: https://files.pythonhosted.org/packages/35/08/f45f8d331010f321df793c9ef72137d674efb2914e6ce7d0fd14a1b4383a/easygui-0.98.1.tar.gz
  sha256: dbc89afbb1aca83830ea4af568eb2491654e16b2706a14d040757fdf1fafbbfe

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - easygui

about:
  home: https://github.com/robertlugg/easygui
  license: BSD
  summary: EasyGUI is a module for very simple, very easy GUI programming in Python
