package:
  name: descartes
  version: !!str 1.0.2

source:
  fn: descartes-1.0.2.tar.gz
  url: https://pypi.python.org/packages/source/d/descartes/descartes-1.0.2.tar.gz
  md5: 2af859c63f73ef852c691f46a06e5938

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - matplotlib
    - numpy

test:
  requires:
    - shapely-win-py27 # [win and py27]
    - nose
  imports:
    - descartes
  commands:
    - nosetests descartes

about:
  home: http://bitbucket.org/sgillies/descartes/
  license:  BSD License
  summary: 'Use geometric objects as matplotlib paths and patches'
