package:
  name: aneris
  version: 0.9.1

source:
  # from git:
  git_url: https://github.com/DTOcean/aneris.git
  git_rev: v0.9.1

build:
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - appdirs:main
    #
    # Would call appdirs.main()
    - bootstrap-dds = aneris.utilities.files:bootstrap_dds_interface
    - xl-merge = aneris.utilities.files:xl_merge_interface

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - attrdict
    - numpy
    - openpyxl
    - pandas
    - polite >=0.9
    - pywin32
    - pyyaml
    - sqlalchemy
    - xlrd
    - xlwt

test:
  # Python imports
  imports:
    - aneris

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: https://github.com/DTOcean/aneris
  license: MIT
  license_file: LICENSE.txt
  summary: Multi-client data coupling agent

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
