package:
  name: geopy
  version: !!str 1.11.0

source:
  fn: geopy-1.11.0.tar.gz
  url: https://pypi.python.org/packages/source/g/geopy/geopy-1.11.0.tar.gz
  md5: b73445dc0069550bbd2b09162f7339b3

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - geopy

about:
  home: https://github.com/geopy/geopy
  license: MIT
  summary: Python Geocoding Toolbox
