package:
  name: psycopg2-win-py27
  version: 2.6.1

source:
  git_url: https://github.com/DTOcean/psycopg2-win32-py27.git [win32 and py27]
  git_rev: v2.6.1

build:
  # The build number should be incremented for new builds of the same version
  number: 0       # (defaults to 0)
#  string: abc     # (defaults to default conda build string plus the build
#                  # number)
#                  # The build string cannot contain a dash '-' character

requirements:
  build:
    - python
    - setuptools
    
test:
  imports:
    - psycopg2

about:
  home: http://initd.org/psycopg
  license: LGPL with exceptions or ZPL
  summary: Python-PostgreSQL Database Adapter

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
