package:
  name: dtocean-dummy-module
  version: 1.0.0

source:
  # from git:
  git_url: https://github.com/DTOcean/dtocean-dummy-module.git
  git_rev: v1.0.0

build:
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - appdirs:main
    #
    # Would call appdirs.main()
    - dtocean-dummy = dtocean_dummy.command:module_interface

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - openpyxl
    - pandas
    - polite >=0.9
    - xlwt
    - xlrd

test:
  # Python imports
  imports:
    - dtocean_dummy
  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - dtocean-dummy 5

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: https://github.com/DTOcean/dtocean-dummy-module
  license: GPLv3
  summary: Dummy module structure used in aneris tests

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
