package:
  name: attrdict
  version: !!str 2.0.0

source:
  fn: utm-0.4.0.tar.gz
  url: https://pypi.python.org/packages/source/a/attrdict/attrdict-2.0.0.tar.gz
  md5: 8a7c1a4e737fe9e2b2b8844c0f7746f8

requirements:
  build:
    - python

  run:
    - python
    - six

test:
  imports:
    - attrdict

about:
  home:  https://github.com/bcj/AttrDict
  license: MIT
  summary: A dict with attribute-style access
