package:
  name: utm
  version: !!str 0.4.0

source:
  fn: utm-0.4.0.tar.gz
  url: https://pypi.python.org/packages/1c/c6/b29ba29537a6cb6ac2f5cddbc5421133c8e1e9beaaba4f489b768d97b2de/utm-0.4.0.tar.gz
  md5: 613a1f0ac10372eff2f313cf24edfe2e

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - utm

about:
  home: https://github.com/Turbo87/utm
  license: MIT
  summary: Bidirectional UTM-WGS84 converter for python
