package:
  name: pypower
  version: !!str 5.0.1

source:
  fn: PYPOWER-5.0.1.tar.gz
  url: https://pypi.python.org/packages/10/b1/caa79c9eb9eaec2d975c7597d42d7defa0af3035a48cc8bde603dd0059bb/PYPOWER-5.0.1.tar.gz
  md5: cec0629c54a2c1d8c3f6ec6f232eaa49

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - scipy

test:
  imports:
    - pypower

about:
  home: https://github.com/rwl/PYPOWER
  license: BSD
  summary: 'Solves power flow and optimal power flow problems'
