package:
  name: dtocean-core
  version: 1.1.dev6

source:
  # from git:
  git_url: https://github.com/DTOcean/dtocean-core.git
  git_rev: v1.1.dev6
  
build:
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - appdirs:main
    #
    # Would call appdirs.main()
    - add-Te = dtocean_core.tools.hydrodynamics:add_Te_interface

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - aneris 0.10.dev2

  run:
    - aneris 0.10.dev2
    - basemap
    - dtocean-hydrodynamics 1.0.0
    - dtocean-electrical 1.1.dev0
    - dtocean-moorings 1.0.0
    - dtocean-installation 1.0.0
    - dtocean-maintenance 1.0.0
    - dtocean-economics 1.0.0
    - dtocean-reliability 1.0.0
    - dtocean-environment 1.0.0
    - geoalchemy2
    - matplotlib
    - monotonic
    - netcdf4
    - numpy 1.10.1
    - openpyxl
    - pandas >=0.18
    - pil
    - polite 0.10.dev1
    - psycopg2
    - pyproj
    - pyqt 4.11.4
    - python-dateutil
    - pyyaml
    - shapely
    - utm
    - xarray
    - xlrd
    - xlwt

test:
  # Python imports
  imports:
    - dtocean_core

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: https://github.com/DTOcean/dtocean-core
  license: GPLv3
  license_file: LICENSE.txt
  summary: The core component of the DTOcean tools

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
