package:
  name: dtocean-qt
  version: 0.9.0

source:
  # from git:
  git_url: https://github.com/DTOcean/dtocean-qt.git
  git_rev: v0.9.0
  
requirements:
  build:
    - python
    - easygui
    - pandas
    - pyqt 4.11.4

  run:
    - python
    - easygui
    - pandas
    - pyqt 4.11.4

test:
  imports:
    - dtocean_qt

about:
  home: https://github.com/DTOcean/dtocean-qt
  license: MIT
  summary: Utilities to use pandas (the data analysis / manipulation library for Python) with Qt
