package:
  name: dtocean-app
  version: 1.0.1

source:
  # from git:
  git_url: https://github.com/DTOcean/dtocean-app.git
  git_rev: v1.0.1
  
build:
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - appdirs:main
    #
    # Would call appdirs.main()
    - dtocean-app = dtocean_app:gui_interface

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - pyqt 4.11.4
    - setuptools

  run:
    - python
    - dtocean-core 1.0.0
    - matplotlib
    - numpy
    - pandas >=0.18
    - dtocean-qt 0.9.1
    - pil
    - polite 0.9.*
    - pyqt 4.11.4

test:
  # Python imports
  imports:
    - dtocean_app

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: https://github.com/DTOcean/dtocean-app
  license: GPLv3
  license_file: LICENSE.txt
  summary: Main application for the DTOcean tools

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
