package:
  name: dtocean-electrical
  version: 1.0.2

source:
  # from git:
  git_url: https://github.com/DTOcean/dtocean-electrical.git
  git_rev: v1.0.2

build:
#   entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - appdirs:main
    #
    # Would call appdirs.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - descartes
    - matplotlib
    - networkx
    - numpy
    - pandas
    - polite 0.9.*
    - pypower
    - pyqt 4.11.4
    - scipy
    - shapely

test:
  # Python imports
  imports:
    - dtocean_electrical

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: https://github.com/DTOcean/dtocean-electrical
  license: GPLv3
  license_file: LICENSE.txt
  summary: Electrical sub-systems module for DTOcean project

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
