package:
  name: shapely-win-py27
  version: 1.5.15

source:
  git_url: https://github.com/DTOcean/Shapely-win32-py27 # [win32 and py27]
  git_rev: v1.5.15

#build:
  # The build number should be incremented for new builds of the same version
#  number: 1       # (defaults to 0)
#  string: abc     # (defaults to default conda build string plus the build
#                  # number)
#                  # The build string cannot contain a dash '-' character

requirements:
  build:
    - python
    - setuptools
    
test:
  imports:
    - shapely

about:
  home: https://github.com/Toblerity/Shapely
  license: BSD
  summary: Geometric objects, predicates, and operations

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
