package:
  name: cma
  version: !!str 2.6.0

source:
  fn: cma-2.6.0.tar.gz
  url: https://files.pythonhosted.org/packages/c0/17/9d93fa7aece6ed28186865b00e375a9facb1c49fa254fab17d758e8e261f/cma-2.6.0.tar.gz
  sha256: ef9e21fd821485518341fe1b96be4d127f8b78e60aeb6a286d602dc98f25eab6

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy

test:
  imports:
    - cma

about:
  home: https://github.com/CMA-ES/pycma
  license: BSD
  summary: CMA-ES, Covariance Matrix Adaptation Evolution Strategy for non-linear numerical optimization in Python
